      - name: Authenticate to Graph
        run: |
          pwsh -command "
            Import-Module Microsoft.Graph.Authentication
            $TenantId = '${{ secrets.TENANT_ID }}'
            $ClientId = '${{ secrets.CLIENT_ID }}'
            $ClientSecret = '${{ secrets.CLIENT_SECRET }}'

            # Build secure credential object
            $SecureSecret = ConvertTo-SecureString $ClientSecret -AsPlainText -Force
            $Cred = New-Object System.Management.Automation.PSCredential ($ClientId, $SecureSecret)

            Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret
            Select-MgProfile -Name beta
          "
