name: "Connect to Intune via Microsoft Graph"

on:
  workflow_dispatch:

jobs:
  connect-intune:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PowerShell
        uses: Amadevus/pwsh-script@v2

      - name: Install Microsoft Graph Module
        run: pwsh -command "Install-Module Microsoft.Graph -Force -Scope CurrentUser"

      - name: Authenticate to Microsoft Graph
        run: pwsh -command "Connect-MgGraph -ClientId '${{ secrets.CLIENT_ID }}' -TenantId '${{ secrets.TENANT_ID }}' -ClientSecret '${{ secrets.CLIENT_SECRET }}'"

      - name: Select Graph Profile
      
        run: pwsh -command "Select-MgProfile -Name beta"

      - name: Test Intune Connection
        run: pwsh -command "Get-MgDeviceManagementIntuneBrandingProfile | Format-Table DisplayName, Id"
