name: "Connect to Intune via Microsoft Graph"

on:
  workflow_dispatch:

jobs:
  connect-intune:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Microsoft Graph Module
        shell: pwsh
        run: |
          Install-Module Microsoft.Graph -Force -Scope CurrentUser
          Import-Module Microsoft.Graph
      - name: Authenticate to Microsoft Graph
        shell: pwsh
        run: |
          $TenantId = '${{ secrets.TENANT_ID }}'
          $ClientId = '${{ secrets.CLIENT_ID }}'
          $ClientSecret = '${{ secrets.CLIENT_SECRET }}'

          Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret
          Select-MgProfile -Name beta

      - name: Test Intune Connection
        shell: pwsh
        run: |
          Get-MgDeviceManagementIntuneBrandingProfile | Format-Table DisplayName, Id
