name: "Deploy Intune Policies"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: Amadevus/pwsh-script@v2

      - name: Install MS Graph Module
        run: pwsh -command "Install-Module Microsoft.Graph.Intune -Force -Scope CurrentUser"

      - name: Authenticate to Graph
        run: |
          pwsh -command "
            Import-Module Microsoft.Graph.Authentication
            $TenantId = '${{ secrets.TENANT_ID }}'
            $ClientId = '${{ secrets.CLIENT_ID }}'
            $ClientSecret = '${{ secrets.CLIENT_SECRET }}'

            Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret
            Select-MgProfile -Name beta
          "
