name: Sync Intune Policies

on:
  push:
    paths:
      - 'Compliance/**/*.json'
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Intune sync script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: pwsh ./scripts/sync-intune.ps1
